export const SEARCH_TRIPS = "SEARCH_TRIPS";
export const GET_STATIONS = "GET_STATIONS";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_TRIPS_LIMIT = "GET_TRIPS_LIMIT";
export const GET_ALL_TRIPS = "GET_ALL_TRIPS";
export const GET_DETAIL_TRIP = "GET_DETAIL_TRIP";

export const SEATS_SELECT = "SEATS_SELECT";
// export const GET_STATIONS = 'GET_STATIONS';
export const CREATE_STATION = "CREATE_STATION";
export const UPDATE_STATION = "UPDATE_STATION";
export const DELETE_STATION = "DELETE_STATION";
export const GET_PAGINATION_STATIONS = "GET_PAGINATION_STATIONS";

export const GET_TRIPS = "GET_TRIPS";
export const CREATE_TRIP = "CREATE_TRIP";
export const UPDATE_TRIP = "UPDATE_TRIP";
export const DELETE_TRIP = "DELETE_TRIP";

export const GET_PROFILE_ADMIN = "GET_PROFILE_ADMIN";
export const UPDATE_PROFILE_ADMIN = "UPDATE_PROFILE_ADMIN";
export const UPDATE_PASSWORD_ADMIN = "UPDATE_PASSWORD_ADMIN";
export const UPDATE_AVATAR = "UPDATE_AVATAR";
export const GET_AVATAR = "GET_AVATAR";
